Repository robotology/icub-main, pull requests merged in 2019-11, with the labels that each got.

#621 Add GitHub Actions-based Continuous Integration
  .github/workflows/ci.yml
Labels: Type: Enhancement

#622 Add the possibility to change the color of the face expression
  app/faceExpressions/conf/emotions_rfe.ini
  src/core/emotionInterface/emotionInterface.h
  src/core/emotionInterface/emotionInterfaceModule.cpp
  src/core/emotionInterface/emotionInterfaceModule.h
Labels: Type: Enhancement

#625 Get rid of Travis CI
  .travis.yml
  README.md
Labels: Complexity: Trivial, Priority: Normal, Type: Cleanup

#614 EmbObj uses std::mutex + std::condition_variable
  src/libraries/icubmod/embObjAnalog/embObjAnalogSensor.cpp
  src/libraries/icubmod/embObjAnalog/embObjAnalogSensor.h
  src/libraries/icubmod/embObjFTsensor/embObjFTsensor.cpp
  src/libraries/icubmod/embObjFTsensor/eo_ftsens_privData.h
  src/libraries/icubmod/embObjInertials/embObjInertials.cpp
  src/libraries/icubmod/embObjInertials/embObjInertials.h
  src/libraries/icubmod/embObjLib/FeatureInterface.cpp
  src/libraries/icubmod/embObjLib/ethManager.cpp
  src/libraries/icubmod/embObjLib/ethManager.h
  src/libraries/icubmod/embObjLib/ethResource.cpp
  src/libraries/icubmod/embObjLib/ethResource.h
  src/libraries/icubmod/embObjLib/fakeEthResource.cpp
  src/libraries/icubmod/embObjLib/fakeEthResource.h
  src/libraries/icubmod/embObjLib/hostTransceiver.cpp
  src/libraries/icubmod/embObjLib/hostTransceiver.hpp
  src/libraries/icubmod/embObjLib/theNVmanager.cpp
  src/libraries/icubmod/embObjMais/embObjMais.cpp
  src/libraries/icubmod/embObjMais/embObjMais.h
  src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
  src/libraries/icubmod/embObjMotionControl/embObjMotionControl.h
  src/libraries/icubmod/embObjMultiEnc/embObjMultiEnc.cpp
  src/libraries/icubmod/embObjMultiEnc/embObjMultiEnc.h
  src/libraries/icubmod/embObjSkin/embObjSkin.cpp
  src/libraries/icubmod/embObjSkin/embObjSkin.h
  src/libraries/icubmod/embObjStrain/embObjStrain.cpp
  src/libraries/icubmod/embObjStrain/embObjStrain.h
  src/tools/embObjProtoTools/boardTransceiver/boardTransceiver.cpp
  src/tools/embObjProtoTools/boardTransceiver/boardTransceiver.hpp
Labels: Complexity: Medium, Priority: Normal, Status: In Progress, Type: Cleanup

#629 [iKin] fixed iCubTorso, iCubEye, iCubArm and iCubInertialSensor kinematics V3
  src/libraries/iKin/src/iKinFwd.cpp
Labels: Complexity: Hard, Priority: High, Severity: Major, Type: Bug
