Repository robotology/icub-main, pull requests merged in 2020-10, with the labels that each got.

#683 FirmwareUpdater - Added new CLI options
  src/tools/FirmwareUpdater/firmwareupdater.ini
  src/tools/FirmwareUpdater/main.cpp
Labels: Type: Enhancement

#684 FirmwareUpdater fixed bug in saveDatFileStrain2
  src/tools/FirmwareUpdater/main.cpp
Labels: Type: Bug

#686 Removed unused firewirebusreset binary
  src/libraries/icubmod/dragonfly2/CMakeLists.txt
  src/libraries/icubmod/dragonfly2/linux/FirewireCameraDC1394-DR2_2.cpp
  src/libraries/icubmod/dragonfly2/linux/FirewireCameraDC1394-DR2_2.h
  src/libraries/icubmod/dragonfly2/linux/fwBusReset_main.cpp
Labels: Type: Cleanup
