Repository robotology/icub-main, pull requests merged in 2020-12, with the labels that each got.

#697 FaceExpressions: update doc.dox
  app/faceExpressions/doc.dox
Labels: Type: Bug, Type: Documentation

#698 faceExpressions: more fixes to the doc
  app/faceExpressions/doc.dox
  app/faceExpressions/scripts/exampleTransition.sh
  src/core/emotionInterface/emotionInterfaceModule.cpp
Labels: Type: Bug, Type: Documentation

#703 embobjMotionControl: fix windows execution
  src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp
Labels: Type: Bug

#708 fixed bug in duplicated command line options
  src/tools/FirmwareUpdater/main.cpp
Labels: Resolution: Fixed, Type: Bug
