Repository robotology/icub-main, pull requests merged in 2020-06, with the labels that each got.

#660 Update face expressions documentation
  app/faceExpressions/doc.dox
  src/doc/face_expressions_rfe.png
Labels: Type: Documentation, Type: Enhancement

#664 Added iCubInertialSensorWaist for iCub v2.7
  src/libraries/iKin/include/iCub/iKin/iKinFwd.h
  src/libraries/iKin/src/iKinFwd.cpp
Labels: Complexity: Medium, Priority: High, Type: Enhancement

#652 Add relocatable CMakeConfig files.
  CMakeLists.txt
  conf/AddInstallRPATHSupport.cmake
  conf/ExtraPackageConfigVars.cmake.in
  conf/ICUBConfig.cmake.in
  conf/iCubDescribe.cmake
  conf/iCubExportBuildTree.cmake
  conf/iCubExportForInstall.cmake
  conf/iCubInstallBasicPackageFiles.cmake
  conf/iCubVersion.cmake
  conf/template/icub-config-build-tree.cmake.in
  conf/template/icub-config-install.cmake.in
  conf/template/icub-config-uninstall.cmake.in
  src/libraries/CMakeLists.txt
  src/libraries/actionPrimitives/CMakeLists.txt
  src/libraries/ctrlLib/CMakeLists.txt
  src/libraries/iCubDev/CMakeLists.txt
  src/libraries/iDyn/CMakeLists.txt
  src/libraries/iKin/CMakeLists.txt
  src/libraries/learningMachine/CMakeLists.txt
  src/libraries/optimization/CMakeLists.txt
  src/libraries/perceptiveModels/CMakeLists.txt
  src/libraries/skinDynLib/CMakeLists.txt
  src/tools/embObjProtoTools/boardTransceiver/CMakeLists.txt
  src/tools/embObjProtoTools/boardTransceiver/CMakeLists.txt.user
Labels: Type: Enhancement
